### PR TITLE
feat: add anonymous fields with type name

### PR DESCRIPTION
**Pull request by sbward**
Enables support for anonymous fields with non-struct types.

### Example

```go
type MyString string

type A struct{
    MyString // Will create a field called `my_string` with VARCHAR/TEXT type
}
```

### CODE REVIEW

**Comment by vmihailenco** [comment]
Is this any better than:

```go
type A struct{
    MyString MyString
}
```

This way it is less code / tests / docs to write and support.

**Comment by sbward** [comment]
My situation is that I want to embed type so that its methods are promoted. If I don't embed it, then I need to manually write each of the methods I want to promote. So in a way, the burden of writing more code and tests is now pushed onto the developer.

I will be happy to add tests and docs to this PR if it will help it get approved :)

**Comment by vmihailenco** [comment]
Looks like encoding/json supports patterns like this so we probably should too.

Please add some tests and maybe comments to the code, because I can't spot any changes in the diff :) I would add a `InsertQuery` test to [query_test.go](https://github.com/uptrace/bun/blob/master/internal/dbtest/query_test.go) and more functional test to [db_test.go](https://github.com/uptrace/bun/blob/master/internal/dbtest/db_test.go).

**Comment by sbward** [comment]
Updated with tests and comments.

**Comment by vmihailenco** [comment]
Looks good, thanks. I will merge this tomorrow.

**Pull request merged**
