### PR TITLE
fix: mssql cursor pagination

### PR DESCRIPTION
**Pull request by lstrihic**
#588

Here is the fix for MSSQL when offset is set to `0`.

### CODE REVIEW

**Comment by vmihailenco** [comment]
Thanks :+1: Could you add a test to https://github.com/uptrace/bun/blob/master/internal/dbtest/query_test.go#L789-L800?

**Comment by lstrihic** [comment]
I just run it locally and everything seems to be fine.
image

**Comment by lstrihic** [comment]
> > The test failure looks real:
> > ```
> > --- FAIL: TestORM (2.64s)
> >     --- FAIL: TestORM/mssql2019 (0.34s)
> >         --- FAIL: TestORM/mssql2019/testAuthorRelations (0.00s)
> >             orm_test.go:132: 
> >                 	Error Trace:	orm_test.go:132
> >                 	            				orm_test.go:43
> >                 	Error:      	Received unexpected error:
> >                 	            	mssql: Invalid usage of the option NEXT in the FETCH statement.
> >                 	Test:       	TestORM/mssql[201](https://github.com/uptrace/bun/runs/6998766509?check_suite_focus=true#step:5:202)9/testAuthorRelations
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any ideas what is wrong?
> 
> I have to check.

In mysql to use limit we have to have defined order.

**Comment by vmihailenco** [comment]
Thanks :+1:

**Pull request merged**
