### PR TITLE
Mssql support

### PR DESCRIPTION
**Pull request by vmihailenco**
Notes
- json type is overwriten to nvarchar(max)
- soft deletes are not supported atm
- upsert is not supported

### CODE REVIEW

**Comment by vmihailenco** [comment]
@gandaldf is there any way to support bulk update in mssql? For example

```sql
WITH "_data" ("id", "title", "author_id", "editor_id", "created_at", "updated_at") AS (VALUES (100, 'book 1', 10, 11, '2022-01-30 07:22:33.047', NULL), (101, 'book 2', 10, 12, '2022-01-30 07:22:33.05', NULL), (102, 'book 3', 11, 11, '2022-01-30 07:22:33.05', NULL)) UPDATE "books" AS "book" SET "title" = UPPER(book.title) FROM "_data" WHERE (book.id = _data.id)
```

**Comment by vmihailenco** [comment]
@gandaldf this should be ready - most tests are passing with mssql. I've created 2 issues to follow up:
- https://github.com/uptrace/bun/issues/429
- https://github.com/uptrace/bun/issues/428

Hopefully you will be able to help with MERGEs :)

Please take a look at this PR and I will merge it to the master branch.

**Comment by iamgoroot** [comment]
@vmihailenco hopefully this fixes things https://github.com/uptrace/bun/pull/440

**Comment by vmihailenco** [comment]
@iamgoroot the build is passing so yes, it does :+1: Thank you.

**Pull request merged**
