### PR TITLE
feat(tag): log with bad tag name

### PR DESCRIPTION
**Pull request by j2gg0s**
Compare sqlName and tag.Name before assign.
This maybe what we expect.

### CODE REVIEW

**Comment by vmihailenco** [comment]
Can you provide the problematic struct tag that you try to handle better with this PR?

**Comment by j2gg0s** [comment]
Struct use tag with known options as name
```
diff --git a/example/basic/main.go b/example/basic/main.go
index 505ec54..85f2664 100644
--- a/example/basic/main.go
+++ b/example/basic/main.go
@@ -89,6 +89,7 @@ type User struct {
        ID     int64
        Name   string
        Emails []string
+       Other  string `bun:"json_use_number"`
 }
```

Run with current:
```
[bun]  23:12:43.259   DROP TABLE              578µs  DROP TABLE IF EXISTS "users"
[bun]  23:12:43.259   CREATE TABLE            329µs  CREATE TABLE "users" ("id" INTEGER NOT NULL, "name" VARCHAR, "emails" VARCHAR, "json_use_number" VARCHAR, PRIMARY KEY ("id"))
[bun]  23:12:43.259   INSERT                  114µs  INSERT INTO "users" ("name", "emails", "json_use_number") VALUES ('admin', '["admin1@admin","admin2@admin"]', '') RETURNING "id"
[bun]  23:12:43.260   INSERT                   95µs  INSERT INTO "users" ("name", "emails", "json_use_number") VALUES ('root', '["root1@root","root2@root"]', '') RETURNING "id"
[bun]  23:12:43.260   DROP TABLE               15µs  DROP TABLE IF EXISTS "stories"
```

Run with this pr will print WARN
```
WARN: bun: 2021/11/01 23:12:54 User.Other tag name "json_use_number" is also an option name; is it a mistake?
[bun]  23:12:54.931   DROP TABLE              674µs  DROP TABLE IF EXISTS "users"
[bun]  23:12:54.932   CREATE TABLE            332µs  CREATE TABLE "users" ("id" INTEGER NOT NULL, "name" VARCHAR, "emails" VARCHAR, "json_use_number" VARCHAR, PRIMARY KEY ("id"))
[bun]  23:12:54.932   INSERT                  130µs  INSERT INTO "users" ("name", "emails", "json_use_number") VALUES ('admin', '["admin1@admin","admin2@admin"]', '') RETURNING "id"
[bun]  23:12:54.932   INSERT                  107µs  INSERT INTO "users" ("name", "emails", "json_use_number") VALUES ('root', '["root1@root","root2@root"]', '') RETURNING "id"
[bun]  23:12:54.932   DROP TABLE               15µs  DROP TABLE IF EXISTS "stories"
```

**Comment by j2gg0s** [comment]
code in branch masnter, compare  `tag.Name` and `sqlName` after assign `tag.Name` to `sqlName`.
It does not make sense.

**Comment by vmihailenco** [comment]
Thanks :+1:

**Pull request merged**
