### PR TITLE
feat: add Join to UpdateQuery

### LINKED ISSUE #907: Missing Join on NewUpdate
Is there a specific reason why `NewUpdate` doesn't have a `Join` method? Would it be possible to add it, or would that be a lot of work?

### PR DESCRIPTION
**Pull request by svanharmelen**
Of course I can remove the second commit if that would block merging this PR!

Fixes #907

### CODE REVIEW

**Comment by svanharmelen** [comment]
@vmihailenco just added a query/example. Let me know if this is OK aka what you meant... Thanks!

**Comment by svanharmelen** [comment]
Hmm, I guess not since it failed 😂 I did run the test on my machine (assuming it would fail and point me in the right direction for adding some stub or test data), but that didn't give me any errors. I will check again, but any pointers on what is needed would be great!

**Comment by svanharmelen** [comment]
Just found the docs and how I should run the tests 🙈 Will push an update in a minute...

**Comment by svanharmelen** [comment]
@vmihailenco added a test (and made sure it succeeds)... Let me know if you need anything else ☺️

**Comment by svanharmelen** [comment]
@vmihailenco anything else you need from my side? Thanks!

**Comment by svanharmelen** [comment]
Anything I can do to get this one merged and released? Would be nice if we can switch back to this package and not have to rely on a `replace` directive in our `go.mod` file 😊

**Comment by vmihailenco** [comment]
@svanharmelen sorry for the delay :+1:

**Comment by svanharmelen** [comment]
Thanks @vmihailenco! Only thing left would be a new tag that includes these changes... Any plan for that already?

**Comment by svanharmelen** [comment]
Thanks for the release @vmihailenco 🎉

**Comment by vmihailenco** [comment]
@svanharmelen thanks for the contribution :+1:

**Pull request merged**
