### PR TITLE
feat(bunotel): add option to enable formatting of queries

### PR DESCRIPTION
**Pull request by matoous**
Disable formatting by default (breaing change)
and add bunotel option that enables formatting.

Formatting has potential to leak information into the traces
as such not formatting the query by default seems like
safer option.

Fixes: https://github.com/uptrace/bun/issues/546

### CODE REVIEW

**Comment by matoous** [comment]
@vmihailenco would you take a look please? This is breaking change, so if you want the default to stay as it is I will have to invert the logic and have option `WithUnfromattedQuery` or maybe `WithFormatting` that would take boolean/flag param.

**Comment by vmihailenco** [comment]
@matoous thanks for the PR.

Let's change `WithFormatting` to accept a boolean flag - I have some reasoning [here](https://blog.uptrace.dev/posts/go-functional-options-named-args.html#bool-options). I am fine with having it disabled by default.

Also, what about renaming `WithFormatting` to `WithFormattedQuery`?

**Comment by matoous** [comment]
@vmihailenco thanks for feedback, updated.

**Comment by vmihailenco** [comment]
Thanks :+1:

**Pull request merged**
