### PR TITLE
feat: support disable dialect's feature

### PR DESCRIPTION
**Pull request by j2gg0s**
Issue: #1045

### CODE REVIEW

**Comment by vmihailenco** [comment]
I'd say this should be done one the dialect level, e.g.:

```go
myDialect := pgdialect.New(pgdialect.WithoutFeature(...))
```

And then the `db` will just use the features from the dialect:

```
db := bun.NewDB(sqldb, myDialect)
```

**Comment by vmihailenco** [comment]
The problem with your current approach is that now we have `bun.DB` with one set of features and `dialect` with another set features. It might be that we currently don't use `dialect.features` anywhere, but it will probably create a problem in the long term.

>And i dont want to add method for every dialect.

We can try to create `BaseDialect` and extract this functionality to the `dialect` package, but TBH it looks easier to just copy/paste 2 simple methods in each package.

**Comment by j2gg0s** [comment]
@vmihailenco 

Let use remove DB.features, and use only the dialect?

**Comment by vmihailenco** [comment]
Looks good :+1: 

I still think that options should be named `WithFeature` and `WithoutFeature`, not `AddFeature` and `RemoveFeature`.

**Review by vmihailenco — APPROVED** [review]

**Pull request merged**
